name: Sync to Hugging Face

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config --global user.email "mona.dhiflaoui@gmail.com"
          git config --global user.name "Mona Dhiflaoui"
      
      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HG }}
        run: |
          git push --force https://monadhif:$HF_TOKEN@huggingface.co/spaces/monadhif/demo main
